[package]
name = "vfd-8md06inkm"
version = "0.1.0"
edition = "2021"

[dependencies]
display-interface = "0.5.0"
display-interface-spi = "0.5.0"
embedded-graphics-core = "0.4.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"

[features]
default = ["graphics"]
graphics = []
